// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2WTKhqz3y8hRBR8FqJZzQZzFDoh9Qgro',
    appId: '1:572033814108:android:00b0d414be400bdbdea099',
    messagingSenderId: '572033814108',
    projectId: 'wave-9c70e',
    storageBucket: 'wave-9c70e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmcPIUk0tbn69JGegKhdzpgiZS7rhIEas',
    appId: '1:572033814108:ios:0f917af4c6df0480dea099',
    messagingSenderId: '572033814108',
    projectId: 'wave-9c70e',
    storageBucket: 'wave-9c70e.appspot.com',
    androidClientId:
        '572033814108-f8jotci7via6rq34ulo5o366j11lcvq5.apps.googleusercontent.com',
    iosClientId:
        '572033814108-865mm4h0ttsvvrp68bgasrrg0esnj5f9.apps.googleusercontent.com',
    iosBundleId: 'com.example.wave',
  );
}
